import "@/server/lib/server-only";

import crypto from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const DEFAULT_DB_PATH = "data/aether.db";
const ENV_FILE_PATH = path.join(process.cwd(), ".env");

let bootstrapCompleted = false;

function generateEncryptionKey() {
  // 32 ASCII characters for the existing AES-256-CBC requirement.
  return crypto.randomBytes(24).toString("base64url").slice(0, 32);
}

function ensureDataDirectory() {
  const dataDirectory = path.join(process.cwd(), "data");
  if (!existsSync(dataDirectory)) {
    mkdirSync(dataDirectory, { recursive: true });
  }
}

export function ensureBootstrapEnv() {
  if (bootstrapCompleted) {
    return;
  }

  const hasDbPath = Boolean(process.env.SQLITE_DB_PATH?.trim());
  const hasEncryptionKey = Boolean(process.env.TOKEN_ENCRYPTION_KEY?.trim());

  if (!hasDbPath) {
    process.env.SQLITE_DB_PATH = DEFAULT_DB_PATH;
  }

  if (!hasEncryptionKey && !existsSync(ENV_FILE_PATH)) {
    ensureDataDirectory();

    const generatedKey = generateEncryptionKey();
    const envContents = [
      "# Auto-generated by Aether on first run.",
      `SQLITE_DB_PATH=${process.env.SQLITE_DB_PATH ?? DEFAULT_DB_PATH}`,
      `TOKEN_ENCRYPTION_KEY=${generatedKey}`,
      "",
    ].join("\n");

    writeFileSync(ENV_FILE_PATH, envContents, { encoding: "utf8", flag: "wx" });
    process.env.TOKEN_ENCRYPTION_KEY = generatedKey;
  }

  bootstrapCompleted = true;
}
